- hosts: all
  tasks:
  - name: Ansible apt with_items example
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - 'make'
      - 'gcc'
      - 'g++'
      - 'rpm'
    become: true
